version: '2.24.4'

services:
  postgres:
    image: postgres
    container_name: fastapiblog_container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6000:5432"
