"""Update user table with tags column

Revision ID: cf266e60729e
Revises: d786cf7f703a
Create Date: 2024-01-31 16:51:11.946810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf266e60729e'
down_revision: Union[str, None] = 'd786cf7f703a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tags')
    # ### end Alembic commands ###
